### ISSUE TITLE
Can0 section may not work at that stage of the guide

### ISSUE THREAD

**Issue by tigitim** [akhamar/voron_canbus_octopus_sb2040#3]
The section getting you to set the can0 file then has you check to see if the network shows up (the `ip a.` and `ip -details -statistics link show can0` ) At this stage of the guide the octopus only has canboot flashed and so **isn't** acting as a USB-CAN bridge and so the CAN network **won't** show up.
This has caused some issues for people following the guide as they thing something has gone wrong at this stage.

I suggest maybe leaving the can0 file creation at this point, but move any network checking until after Klipper itself is flashed to the octopus (but before flashing klipper to the SB2040).

**Comment by akhamar** [comment]
Done
